# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zpid', models.IntegerField()),
                ('details_url', models.URLField()),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zestimate', models.IntegerField()),
                ('rent_cost', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('sq_ft', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comp_score', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
